Repository AuroraEditor/AuroraEditor, pull requests merged in 2022-08, with the labels that each got.

#82 Added new git icons and remove `Light-Swift-Untar`
  AuroraEditor.xcodeproj/project.pbxproj
  AuroraEditor.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  AuroraEditor/.githash
  AuroraEditor/Assets.xcassets/Git/Contents.json
  AuroraEditor/Assets.xcassets/Git/git.branch.symbolset/Contents.json
  AuroraEditor/Assets.xcassets/Git/git.branch.symbolset/git.branch.svg
  AuroraEditor/Assets.xcassets/Git/git.commit.symbolset/Contents.json
  AuroraEditor/Assets.xcassets/Git/git.commit.symbolset/git.commit.svg
  AuroraEditor/Assets.xcassets/Git/git.fork.symbolset/Contents.json
  AuroraEditor/Assets.xcassets/Git/git.fork.symbolset/git.fork.svg
  AuroraEditor/Assets.xcassets/Git/git.merge.symbolset/Contents.json
  AuroraEditor/Assets.xcassets/Git/git.merge.symbolset/git.merge.svg
  AuroraEditor/Assets.xcassets/Git/git.pullrequest.symbolset/Contents.json
  AuroraEditor/Assets.xcassets/Git/git.pullrequest.symbolset/git.pullrequest.svg
  AuroraEditor/Base/Extensions/Models/ExtensionsManager.swift
  AuroraEditor/Base/NavigatorSidebar/Model/SourceControlNavigator/Repositories/RepositoriesTableViewCell.swift
  AuroraEditor/Base/NavigatorSidebar/Model/SourceControlNavigator/Repositories/RepositoriesViewController.swift
  AuroraEditor/Base/NavigatorSidebar/UI/SourceControlNavigator/SourceControlNavigatorView.swift
  AuroraEditor/Base/Toolbar/UI/ToolbarBranchPicker.swift
Labels: enhancement

#83 Moved to AEExtensionKit
  AuroraEditor.xcodeproj/project.pbxproj
  AuroraEditor/.githash
  AuroraEditor/Base/Documents/Model/WorkspaceCodeFileView.swift
  AuroraEditor/Base/Documents/Model/WorkspaceDocument.swift
  AuroraEditor/Base/Extensions/Models/AuroraEditorAPI.swift
  AuroraEditor/Base/Extensions/Models/AuroraEditorTargetsAPI.swift
  AuroraEditor/Base/Extensions/Models/ExtensionsManager.swift
  AuroraEditor/Base/Extensions/Models/Plugin.swift
  AuroraEditor/Base/Git/Models/Client/Checkout.swift
  AuroraEditor/Base/Git/Models/Client/Stash.swift
  AuroraEditor/Base/WorkspaceClient/Model/WorkspaceClient/WorkspaceClient.swift
  AuroraEditor/Utils/String/String.swift
  Package.resolved
Labels: enhancement, Architecture

#86 Update Discord link
  README.md
Labels: bug, enhancement

#92 Update README.md
  README.md
Labels: enhancement

#88 Fix tabs not receiving text updates, fixes #87
  .github/workflows/Build.yml
  .github/workflows/SwiftLint.yml
  .swiftlint.yml
  AuroraEditor.xcodeproj/project.pbxproj
  AuroraEditor/.githash
  AuroraEditor/Assets.xcassets/Git/git.branch.symbolset/git.branch.svg
  AuroraEditor/Assets.xcassets/Git/git.commit.symbolset/git.commit.svg
  AuroraEditor/Assets.xcassets/Git/git.merge.symbolset/git.merge.svg
  AuroraEditor/Assets.xcassets/Git/git.pullrequest.symbolset/git.pullrequest.svg
  AuroraEditor/Base/AuroraEditorTextView/UI/STTextViewController+STTextViewDelegate.swift
  AuroraEditor/Base/Documents/Model/WorkspaceDocument+Tabs.swift
  AuroraEditor/Base/Documents/Model/WorkspaceDocument.swift
  AuroraEditor/Base/Git/Models/Client/Branch.swift
  AuroraEditor/Base/Git/Models/Client/Helpers/GitError.swift
  AuroraEditor/Base/Git/Models/Client/Remote.swift
  AuroraEditor/Base/Git/Models/Client/Rev-List.swift
  AuroraEditor/Base/Git/Models/Client/Rev-Parse.swift
  AuroraEditor/Symbols.xcassets/Contents.json
  AuroraEditor/Symbols.xcassets/breakpoint.fill.symbolset/Contents.json
  AuroraEditor/Symbols.xcassets/breakpoint.fill.symbolset/breakpoint.fill.svg
  AuroraEditor/Symbols.xcassets/breakpoint.symbolset/Contents.json
  AuroraEditor/Symbols.xcassets/breakpoint.symbolset/breakpoint.svg
  AuroraEditor/Symbols.xcassets/checkout.symbolset/Contents.json
  AuroraEditor/Symbols.xcassets/checkout.symbolset/checkout.svg
  AuroraEditor/Symbols.xcassets/commit.symbolset/Contents.json
  AuroraEditor/Symbols.xcassets/commit.symbolset/commit.svg
  AuroraEditor/Symbols.xcassets/custom.chevron.up.chevron.down.symbolset/Contents.json
  AuroraEditor/Symbols.xcassets/custom.chevron.up.chevron.down.symbolset/custom.chevron.up.chevron.down.svg
  AuroraEditor/Symbols.xcassets/vault.fill.symbolset/Contents.json
  AuroraEditor/Symbols.xcassets/vault.fill.symbolset/vault.fill.svg
  AuroraEditor/Symbols.xcassets/vault.symbolset/Contents.json
  AuroraEditor/Symbols.xcassets/vault.symbolset/vault.svg
  AuroraEditor/Utils/AuroraEditorSymbols.swift
  Package.resolved
Labels: bug, Editor

#103 Fix SwiftUI previews
  AuroraEditor.xcodeproj/project.pbxproj
  AuroraEditor/.githash
Labels: bug

#104 disable macOS 11 test
  .github/workflows/Build.yml.disabled
  .github/workflows/SwiftLint.yml
Labels: bug, enhancement

#105 re-setup GH Actions
  .github/workflows/Build.yml
  .github/workflows/SwiftLint.yml
Labels: bugfix

#107 Fixed saving, fixes #106
  AuroraEditor/.githash
  AuroraEditor/Base/AuroraEditorTextView/UI/STTextViewController+STTextViewDelegate.swift
Labels: bugfix

#109 Updated workflow (to create one test)
  .github/workflows/Build.yml
  .github/workflows/workflow.yml
  AuroraEditor/.githash
Labels: enhancement

#85 Migration of preferences
  AuroraEditor.xcodeproj/project.pbxproj
  AuroraEditor.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  AuroraEditor/.githash
  AuroraEditor/AppDelegate.swift
  AuroraEditor/Base/AppPreferences/Controller/PreferencesWindowController.swift
  AuroraEditor/Base/AppPreferences/HelperViews/PreferencesSection.swift
  AuroraEditor/Base/AppPreferences/Model/Accounts/SourceControlAccounts.swift
  AuroraEditor/Base/AppPreferences/Model/General/GeneralPreferences.swift
  AuroraEditor/Base/AppPreferences/Model/SettingItem.swift
  AuroraEditor/Base/AppPreferences/Model/SettingsModel.swift
  AuroraEditor/Base/AppPreferences/UI/AccountsPreferences/AccountItemView.swift
  AuroraEditor/Base/AppPreferences/UI/AccountsPreferences/AccountListItem.swift
  AuroraEditor/Base/AppPreferences/UI/AccountsPreferences/AccountSelectionDialog.swift
  AuroraEditor/Base/AppPreferences/UI/AccountsPreferences/Login/Github/GithubEnterpriseLoginView.swift
  AuroraEditor/Base/AppPreferences/UI/AccountsPreferences/Login/Github/GithubLoginView.swift
  AuroraEditor/Base/AppPreferences/UI/AccountsPreferences/Login/Gitlab/GitlabHostedLoginView.swift
  AuroraEditor/Base/AppPreferences/UI/AccountsPreferences/Login/Gitlab/GitlabLoginView.swift
  AuroraEditor/Base/AppPreferences/UI/AccountsPreferences/PreferenceAccountsView.swift
  AuroraEditor/Base/AppPreferences/UI/GeneralPreferences/GeneralPreferencesView.swift
  AuroraEditor/Base/AppPreferences/UI/LocationsPreferences/LocationsPreferencesView.swift
  AuroraEditor/Base/AppPreferences/UI/PreferencesPlaceholderView.swift
  AuroraEditor/Base/AppPreferences/UI/PreferencesView.swift
  AuroraEditor/Base/AppPreferences/UI/SourceControlPreferences/PreferenceSourceControlView.swift
  AuroraEditor/Base/AppPreferences/UI/SourceControlPreferences/SourceControlGeneralView.swift
  AuroraEditor/Base/AppPreferences/UI/SourceControlPreferences/SourceControlGitView.swift
  AuroraEditor/Base/AppPreferences/UI/TerminalPreferences/TerminalPreferencesView.swift
  AuroraEditor/Base/AppPreferences/UI/TextEditingPreferences/TextEditingPreferencesView.swift
  AuroraEditor/Base/AppPreferences/UI/ThemePreferences/ThemePreferencesView.swift
  AuroraEditor/Utils/GroupBox.swift
Labels: UI

#110 Multiple bugfixes
  AuroraEditor/.githash
  AuroraEditor/Base/AppPreferences/Controller/PreferencesWindowController.swift
  AuroraEditor/Base/AppPreferences/Model/SettingsModel.swift
  AuroraEditor/Base/AppPreferences/Model/ThemePreferences/Theme+Highlightr.swift
  AuroraEditor/Base/AppPreferences/UI/PreferencesView.swift
  AuroraEditor/Base/AuroraEditorTextView/UI/STTextViewController.swift
  AuroraEditor/Base/TabBar/UI/TabBarItem.swift
  Package.resolved
Labels: bugfix

#113 Super big sync
  .all-contributorsrc
  .github/scripts/remove_todos.sh
  .github/scripts/test_app.sh
  .github/stale.yml
  AuroraEditor/.githash
  AuroraEditor/Base/AppPreferences/Model/AppPreferencesModel.swift
  AuroraEditor/Base/AppPreferences/Model/ThemePreferences/ThemeModel.swift
  CONTRIBUTING.md
Labels: enhancement

#118 UI Fixes
  AuroraEditor/.githash
  AuroraEditor/Base/NavigatorSidebar/UI/SourceControlNavigator/Changes/CommitChangesView.swift
  AuroraEditor/Base/NavigatorSidebar/UI/SourceControlNavigator/Repositories/CreateNewRepositoryView.swift
Labels: Version control, bugfix, user interface

#120 Add partial spilt view
  AuroraEditor.xcodeproj/project.pbxproj
  AuroraEditor/Base/Documents/UI/WorkspaceCodeFileView.swift
  AuroraEditor/Base/Git/Models/Accounts/Gitlab/Model/Namespace.swift
  AuroraEditor/Base/Git/Models/Accounts/Gitlab/Model/Project.swift
  AuroraEditor/Base/NavigatorSidebar/UI/NavigatorSidebar.swift
  AuroraEditor/Utils/SplitView/DropProposalPositionCalculations.swift
  AuroraEditor/Utils/SplitView/SplitEditorDropProposalPosition.swift
  AuroraEditor/Utils/SplitView/SplitViewDropDelegate.swift
  AuroraEditor/Utils/SplitView/SplitViewDropProposalOverlay.swift
  AuroraEditor/Utils/SplitView/SplitViewModifier.swift
Labels: enhancement, UI, Editor, user interface

#123 Show alert view on error
  AuroraEditor.xcodeproj/project.pbxproj
  AuroraEditor/.githash
  AuroraEditor/Base/InspectorSidebar/UI/FileInspector/FileInspectorView.swift
  AuroraEditor/Utils/Log/Log.swift
  AuroraEditor/Utils/auroraMessageBox.swift
Labels: enhancement

#131 Fixed #124
  AuroraEditor/Base/Documents/UI/WorkspaceCodeFileView.swift
  AuroraEditor/Base/Documents/UI/WorkspaceView.swift
Labels: bugfix

#129 Add web tab
  AuroraEditor.xcodeproj/project.pbxproj
  AuroraEditor/.githash
  AuroraEditor/Base/Documents/Model/WorkspaceDocument+Selection.swift
  AuroraEditor/Base/Documents/Model/WorkspaceDocument+Tabs.swift
  AuroraEditor/Base/Documents/UI/WorkspaceView.swift
  AuroraEditor/Base/TabBar/Model/TabBarItemID.swift
  AuroraEditor/Base/TabBar/UI/TabBar.swift
  AuroraEditor/Base/Toolbar/UI/ToolbarPlusMenu.swift
  AuroraEditor/Base/WebView/WebTab.swift
  AuroraEditor/Base/WebView/WebTabView.swift
  AuroraEditor/Base/WebView/WebView.swift
  AuroraEditor/Base/WorkspaceClient/Model/FileItem/FileItemFileSystemFunctions.swift
Labels: enhancement, UI

#141 Fixed issue #126, and when clicking on the STTextViewController, the cursor will go to the end of file
  AuroraEditor/.githash
  AuroraEditor/Base/AuroraEditorTextView/STTextView/Model/STTextView+CopyPaste.swift
  AuroraEditor/Base/AuroraEditorTextView/UI/STTextViewController.swift
Labels: enhancement, Editor, bugfix
