Repository AuroraEditor/AuroraEditor, pull requests merged in 2023-09, with the labels that each got.

#440 Fixes crash of minimap, fixes #439
  AuroraEditor/Base/Editor/CodeEditorView/UI/CodeView.swift
Labels: bugfix

#443 Fix force unwrapping of themes, fixes #442
  AuroraEditor/Base/Documents/UI/CodeEditorViewWrapper.swift
  AuroraEditor/Base/Editor/CodeEditorView/UI/CodeEditorView.swift
  AuroraEditor/Base/Editor/CodeEditorView/UI/CodeView.swift
  AuroraEditor/Base/Editor/EditorCore/Theme/Theme Attributes/BackgroundColorThemeAttribute.swift
Labels: UI, bugfix

#447 Render markdown in about, fixes #446
  AuroraEditor/Base/About/UI/CreditsDetailView.swift
  AuroraEditor/Base/About/UI/LicenseDetailView.swift
  AuroraEditor/Resources/Credits.md
Labels: UI, bugfix

#449 Update Project action
  .github/workflows/project.yml
Labels: bugfix

#454 Change MenuBarIcon depending on system appearance, fixes #445
  AuroraEditor/Assets.xcassets/MenuBar/MenuBarIcon.imageset/Contents.json
  AuroraEditor/Assets.xcassets/MenuBar/MenuBarIcon.imageset/Icon-light.svg
  AuroraEditor/Assets.xcassets/MenuBar/MenuBarIcon.imageset/icon-dark 1.svg
  AuroraEditor/Assets.xcassets/MenuBar/MenuBarIcon.imageset/icon-dark 2.svg
Labels: UI, user experience

#458 Add ini parser, made some tests
  .swiftlint.yml
  Aurora Editor UITests/Aurora_Editor_UITests.swift
  Aurora Editor UITests/Aurora_Editor_UITestsLaunchTests.swift
  Aurora Editor.xcodeproj/project.pbxproj
  Aurora Editor.xcodeproj/xcshareddata/xcschemes/Aurora Editor (Release).xcscheme
  Aurora Editor.xcodeproj/xcshareddata/xcschemes/Aurora Editor (Tests).xcscheme
  Aurora Editor.xcodeproj/xcshareddata/xcschemes/Aurora Editor.xcscheme
  Aurora EditorTests/AuroraINITests.swift
  AuroraEditor/Utils/AuroraINIParser.swift
Labels: enhancement, Testing

#461 Make hidden buttons unfocusable, fixes #441
  AuroraEditor/Base/WelcomeModule/UI/WelcomeWindowView.swift
Labels: UI, bugfix

#460 Close feedback window after feedback, closes #459
  AuroraEditor/Base/Feedback/Controllers/FeedbackWindowController.swift
  AuroraEditor/Base/Feedback/Model/FeedbackModel.swift
Labels: UI, bugfix

#463 Small fix for settings
  AuroraEditor/Base/AppPreferences/UI/GeneralPreferences/GeneralPreferencesViewSections.swift
Labels: UI, bugfix, Localization

#470 Fix double 'variable', fixes #469
  AuroraEditor/Base/AppPreferences/Model/ThemePreferences/ThemeJsonLoader/ThemeJsonLoader+AuroraTheme(Old).swift
Labels: bugfix, Theme

#471 Fix trying to overwrite/copy files, fixes #467
  AuroraEditor/Base/AppPreferences/Model/ThemePreferences/ThemeModel.swift
Labels: bugfix, Theme

#474 `Text` to `LocalizedStringKey`, fixes #473
  AuroraEditor/Base/AppPreferences/HelperViews/PreferencesColorPicker.swift
Labels: UI, bugfix, Theme, Localization

#476 Fixed layout width, Fixes #475
  AuroraEditor/Base/AppPreferences/UI/ThemePreferences/TerminalThemeView.swift
Labels: UI, bugfix

#477 Refactor update checker
  AuroraEditor/Base/AppPreferences/Model/Updates/UpdateModel.swift
Labels: SwiftLint, bugfix

#478 Fix some xcode 15 warnings
  AuroraEditor/Base/AuroraEditorUI/Model/OverlayPanel.swift
  AuroraEditor/Base/Documents/Model/AuroraEditorWindow/AuroraEditorWindowController+NSToolbarDelegate.swift
  AuroraEditor/Base/Documents/Model/AuroraEditorWindow/AuroraEditorWindowController.swift
  AuroraEditor/Base/Documents/UI/AuroraSplitViewController.swift
  AuroraEditor/Base/Documents/UI/WorkspaceView.swift
  AuroraEditor/Base/Editor/EditorCore/Theme/Theme Attributes/BackgroundColorThemeAttribute.swift
  AuroraEditor/Base/Editor/EditorCore/Theme/Theme Attributes/BoldThemeAttribute.swift
  AuroraEditor/Base/Editor/EditorCore/Theme/Theme Attributes/DefaultTabIntervalThemeAttribute.swift
  AuroraEditor/Base/Editor/EditorCore/Theme/Theme Attributes/FirstLineHeadIndentThemeAttribute.swift
  AuroraEditor/Base/Editor/EditorCore/Theme/Theme Attributes/FontThemeAttribute.swift
  AuroraEditor/Base/Editor/EditorCore/Theme/Theme Attributes/HeadIndentThemeAttribute.swift
  AuroraEditor/Base/Editor/EditorCore/Theme/Theme Attributes/ItalicThemeAttribute.swift
  AuroraEditor/Base/Editor/EditorCore/Theme/Theme Attributes/LineHeightThemeAttribute.swift
  AuroraEditor/Base/Editor/EditorCore/Theme/Theme Attributes/ParagraphSpacingAfterThemeAttribute.swift
  AuroraEditor/Base/Editor/EditorCore/Theme/Theme Attributes/ParagraphSpacingBeforeThemeAttribute.swift
  AuroraEditor/Base/Editor/EditorCore/Theme/Theme Attributes/TabStopsThemeAttribute.swift
  AuroraEditor/Base/Editor/EditorCore/Theme/Theme Attributes/TailIndentThemeAttribute.swift
  AuroraEditor/Base/Editor/EditorCore/Theme/Theme Attributes/TextAlignmentThemeAttribute.swift
  AuroraEditor/Base/Editor/EditorCore/Theme/Theme Attributes/TextBlockThemeAttribute.swift
  AuroraEditor/Base/Editor/EditorCore/Theme/Theme Attributes/UndlerlineColorThemeAttribute.swift
  AuroraEditor/Base/NavigatorSidebar/Model/ExtensionNavigator/ExtensionInstallationViewModel.swift
  AuroraEditor/Base/NavigatorSidebar/Model/FindNavigator/SearchResultMatchModel.swift
  AuroraEditor/Base/NavigatorSidebar/UI/ExtensionNavigator/ExtensionNavigatorView.swift
  AuroraEditor/Base/Version Control/Model/Accounts/Bitbucket/BitbucketAccount+Token.swift
  AuroraEditor/Base/Version Control/Model/Accounts/Bitbucket/Model/BitbucketRepositories.swift
  AuroraEditor/Base/Version Control/Model/Accounts/Bitbucket/Model/BitbucketUser.swift
Labels: bugfix

#499 Enhancements to Localization String Extraction Script
  .swiftlint.yml
  Aurora Editor.xcodeproj/project.pbxproj
  Tools/ExtractLocalizationStrings.swift
  Tools/xstrings.swift
Labels: Script, Translations, Localization

#504 Add Sentry as sponsor for AuroraEditor
  README.md
Labels: Readme, Sponsorship

#528 Fix "Implement basic git commit functionality" #527
  Aurora Editor.xcodeproj/project.pbxproj
Labels: bugfix

#529 Fix version number on about screen, fixes #465
  AuroraEditor/Base/About/UI/ApplicationsDetailsView.swift
  AuroraEditor/Localization/Localized+Ex.swift
Labels: UI, bugfix
