Repository AuroraEditor/AuroraEditor, pull requests merged in 2023-02, with the labels that each got.

#416 Add localise strings to `AppPreferences` & `About`
  AuroraEditor/Base/About/UI/ApplicationsDetailsView.swift
  AuroraEditor/Base/AppPreferences/UI/AccountsPreferences/AccountItemView.swift
  AuroraEditor/Base/AppPreferences/UI/AccountsPreferences/AccountSelectionDialog.swift
  AuroraEditor/Base/AppPreferences/UI/AccountsPreferences/Login/AuroraEditor/AuroraEditorLoginView.swift
  AuroraEditor/Base/AppPreferences/UI/AccountsPreferences/Login/Github/GithubEnterpriseLoginView.swift
  AuroraEditor/Base/AppPreferences/UI/AccountsPreferences/Login/Github/GithubLoginView.swift
  AuroraEditor/Base/AppPreferences/UI/AccountsPreferences/Login/Gitlab/GitlabHostedLoginView.swift
  AuroraEditor/Base/AppPreferences/UI/AccountsPreferences/Login/Gitlab/GitlabLoginView.swift
  AuroraEditor/Base/AppPreferences/UI/AccountsPreferences/PreferenceAccountsView.swift
  AuroraEditor/Base/AppPreferences/UI/GeneralPreferences/GeneralPreferencesView.swift
  AuroraEditor/Base/AppPreferences/UI/GeneralPreferences/GeneralPreferencesViewSections.swift
  AuroraEditor/Base/AppPreferences/UI/SourceControlPreferences/PreferenceSourceControlView.swift
  AuroraEditor/Base/AppPreferences/UI/SourceControlPreferences/SourceControlGeneralView.swift
  AuroraEditor/Base/AppPreferences/UI/SourceControlPreferences/SourceControlGitView.swift
  AuroraEditor/Base/AppPreferences/UI/TerminalPreferences/TerminalPreferencesView.swift
  AuroraEditor/Base/AppPreferences/UI/TextEditingPreferences/TextEditingPreferencesView.swift
  AuroraEditor/Base/AppPreferences/UI/ThemePreferences/EditorThemeAttributeView.swift
  AuroraEditor/Base/AppPreferences/UI/ThemePreferences/EditorThemeView.swift
  AuroraEditor/Base/AppPreferences/UI/ThemePreferences/PreviewThemeView.swift
  AuroraEditor/Base/AppPreferences/UI/ThemePreferences/TerminalThemeView.swift
  AuroraEditor/Base/AppPreferences/UI/ThemePreferences/ThemePreferencesView.swift
  AuroraEditor/Base/AppPreferences/UI/UpdatesPreferences/AutomaticallyUpdateSheet.swift
  AuroraEditor/Base/AppPreferences/UI/UpdatesPreferences/UpdatePreferencesView.swift
  AuroraEditor/Localization/af.lproj/Localizable.strings
  AuroraEditor/Localization/cs.lproj/Localizable.strings
  AuroraEditor/Localization/cy.lproj/Localizable.strings
  AuroraEditor/Localization/da.lproj/Localizable.strings
  AuroraEditor/Localization/de.lproj/Localizable.strings
  AuroraEditor/Localization/el.lproj/Localizable.strings
  AuroraEditor/Localization/en-001.lproj/Localizable.strings
  AuroraEditor/Localization/en.lproj/Localizable.strings
  AuroraEditor/Localization/es.lproj/Localizable.strings
  AuroraEditor/Localization/fi.lproj/Localizable.strings
  AuroraEditor/Localization/fil.lproj/Localizable.strings
  AuroraEditor/Localization/fr.lproj/Localizable.strings
  AuroraEditor/Localization/ga.lproj/Localizable.strings
  AuroraEditor/Localization/hi.lproj/Localizable.strings
  AuroraEditor/Localization/hr.lproj/Localizable.strings
  AuroraEditor/Localization/it.lproj/Localizable.strings
  AuroraEditor/Localization/ja.lproj/Localizable.strings
  AuroraEditor/Localization/ms.lproj/Localizable.strings
  AuroraEditor/Localization/mt.lproj/Localizable.strings
  AuroraEditor/Localization/nb.lproj/Localizable.strings
  AuroraEditor/Localization/ne.lproj/Localizable.strings
  AuroraEditor/Localization/nl.lproj/Localizable.strings
  AuroraEditor/Localization/pl.lproj/Localizable.strings
  AuroraEditor/Localization/pt-PT.lproj/Localizable.strings
  AuroraEditor/Localization/ro.lproj/Localizable.strings
  AuroraEditor/Localization/ru.lproj/Localizable.strings
  AuroraEditor/Localization/sv.lproj/Localizable.strings
  AuroraEditor/Localization/th-TH.lproj/Localizable.strings
  AuroraEditor/Localization/th.lproj/Localizable.strings
  AuroraEditor/Localization/tn.lproj/Localizable.strings
  AuroraEditor/Localization/uk.lproj/Localizable.strings
  AuroraEditor/Localization/vi.lproj/Localizable.strings
  AuroraEditor/Localization/xh-ZA.lproj/Localizable.strings
  AuroraEditor/Localization/zh-HK.lproj/Localizable.strings
  AuroraEditor/Localization/zh-Hans.lproj/Localizable.strings
  AuroraEditor/Localization/zh-Hant.lproj/Localizable.strings
  AuroraEditor/Localization/zu-ZA.lproj/Localizable.strings
Labels: Translation

#420 Make Preferences window resizable so that user can see all of contents.
  AuroraEditor/Base/AppPreferences/Controller/PreferencesWindowController.swift
  AuroraEditor/Base/AppPreferences/UI/PreferencesView.swift
Labels: UI, bugfix

#423 Check SwiftLint version
  Aurora Editor.xcodeproj/project.pbxproj
Labels: Architecture, SwiftLint

#424 Fixed some swiftlint errors
  Aurora Editor.xcodeproj/project.pbxproj
  AuroraEditor/Base/About/UI/AboutView.swift
  AuroraEditor/Base/AppPreferences/Model/ThemePreferences/ThemeJsonLoader/ThemeJsonLoader+AuroraTheme(Old).swift
  AuroraEditor/Base/Documents/Model/AuroraEditorWindow/AuroraDataStorage.swift
  AuroraEditor/Base/Editor/EditorCore/Theme/HighlightTheme.swift
  AuroraEditor/Base/FileCreation/Model/FileCreationModel.swift
  AuroraEditor/Base/FileCreation/UI/FileCreationSelectionView.swift
Labels: SwiftLint

#425 Remember splitView width of AuroraEditorWindow
  Aurora Editor.xcodeproj/project.pbxproj
  AuroraEditor/Base/AppPreferences/Model/General/GeneralPreferences.swift
  AuroraEditor/Base/Documents/Model/AuroraEditorWindow/AuroraEditorWindowController.swift
  AuroraEditor/Base/Documents/Model/WorkspaceDocument/WorkspaceDocument.swift
  AuroraEditor/Base/Documents/UI/AuroraSplitViewController.swift
Labels: UI, Architecture
