Repository AuroraEditor/AuroraEditor, pull requests merged in 2023-10, with the labels that each got.

#531 Fix building after version-control changes
  Aurora Editor.xcodeproj/project.pbxproj
  AuroraEditor/Base/NavigatorSidebar/Model/SourceControlNavigator/Changes/SourceControlModel.swift
  AuroraEditor/Base/NavigatorSidebar/Model/SourceControlNavigator/Repositories/RepositoriesMenu.swift
  AuroraEditor/Base/NavigatorSidebar/Model/SourceControlNavigator/Repositories/RepositoryModel.swift
  AuroraEditor/Base/NavigatorSidebar/UI/SourceControlNavigator/Repositories/CreateNewRepositoryView.swift
  AuroraEditor/Base/Version Control/Model/Client/Core/GitClient.swift
  AuroraEditor/Base/Version Control/UI/Branch/CreateNewBranchView.swift
  AuroraEditor/Base/Version Control/UI/Clone/GitCloneView.swift
  AuroraEditor/Base/Version Control/UI/Rename/RenameBranchView.swift
  AuroraEditor/Base/Version Control/UI/Tag/CreateNewTagView.swift
Labels: Version control, bugfix, hacktoberfest, hacktoberfest-accepted

#538 Fixed clipped color text and added scrollview
  AuroraEditor/Base/AppPreferences/UI/ThemePreferences/TerminalThemeView.swift
Labels: UI, bugfix, hacktoberfest, hacktoberfest-accepted

#544 Fix PreferencesColorPicker
  AuroraEditor/Base/AppPreferences/HelperViews/PreferencesColorPicker.swift
Labels: bugfix, hacktoberfest, hacktoberfest-accepted

#542 Enhancement: Introducing Editor Update System
  .swiftlint.yml
  AEUpdateService/AEUpdateService.entitlements
  AEUpdateService/AEUpdateServiceApp.swift
  AEUpdateService/Animation/Loader.swift
  AEUpdateService/Animation/LoaderState.swift
  AEUpdateService/Animation/LoaderView.swift
  AEUpdateService/Assets.xcassets/AccentColor.colorset/Contents.json
  AEUpdateService/Assets.xcassets/AppIcon.appiconset/Contents.json
  AEUpdateService/Assets.xcassets/AppIcon.appiconset/icon_128x128.png
  AEUpdateService/Assets.xcassets/AppIcon.appiconset/icon_128x128@2x.png
  AEUpdateService/Assets.xcassets/AppIcon.appiconset/icon_16x16.png
  AEUpdateService/Assets.xcassets/AppIcon.appiconset/icon_16x16@2x.png
  AEUpdateService/Assets.xcassets/AppIcon.appiconset/icon_256x256.png
  AEUpdateService/Assets.xcassets/AppIcon.appiconset/icon_256x256@2x.png
  AEUpdateService/Assets.xcassets/AppIcon.appiconset/icon_32x32.png
  AEUpdateService/Assets.xcassets/AppIcon.appiconset/icon_32x32@2x.png
  AEUpdateService/Assets.xcassets/AppIcon.appiconset/icon_512x512.png
  AEUpdateService/Assets.xcassets/AppIcon.appiconset/icon_512x512@2x.png
  AEUpdateService/Assets.xcassets/Contents.json
  AEUpdateService/Assets.xcassets/UpdateImage.imageset/Contents.json
  AEUpdateService/Assets.xcassets/UpdateImage.imageset/undraw_programming_re_kg9v.svg
  AEUpdateService/ContentView.swift
  AEUpdateService/Extensions/URL.swift
  AEUpdateService/Main.swift
  AEUpdateService/Preview Content/Preview Assets.xcassets/Contents.json
  AEUpdateService/Service/AEUpdateService.swift
  Aurora Editor.xcodeproj/project.pbxproj
  Aurora Editor.xcodeproj/xcshareddata/xcschemes/AEUpdateService.xcscheme
  Aurora Editor.xcodeproj/xcshareddata/xcschemes/Aurora Editor.xcscheme
  AuroraEditor/Base/AppPreferences/Controller/PreferencesWindowController.swift
  AuroraEditor/Base/AppPreferences/Model/Updates/UpdateEditorRepository.swift
  AuroraEditor/Base/AppPreferences/Model/Updates/UpdateModel.swift
  AuroraEditor/Base/AppPreferences/Model/Updates/UpdatePreferences.swift
  AuroraEditor/Base/AppPreferences/UI/UpdatesPreferences/Update States/UpdateAvailableState.swift
  AuroraEditor/Base/AppPreferences/UI/UpdatesPreferences/Update States/UpdateCancelledState.swift
  AuroraEditor/Base/AppPreferences/UI/UpdatesPreferences/Update States/UpdateErrorState.swift
  AuroraEditor/Base/AppPreferences/UI/UpdatesPreferences/Update States/UpdateInProgressState.swift
  AuroraEditor/Base/AppPreferences/UI/UpdatesPreferences/Update States/UpdateInvalidChecksumState.swift
  AuroraEditor/Base/AppPreferences/UI/UpdatesPreferences/Update States/UpdateLoadingState.swift
  AuroraEditor/Base/AppPreferences/UI/UpdatesPreferences/Update States/UpdateReadyState.swift
  AuroraEditor/Base/AppPreferences/UI/UpdatesPreferences/Update States/UpdateUpToDateState.swift
  AuroraEditor/Base/AppPreferences/UI/UpdatesPreferences/UpdatePreferencesView.swift
  AuroraEditor/Base/AppPreferences/UI/UpdatesPreferences/Util Views/LicenseView.swift
  AuroraEditor/Base/Git/Models/Diff/Diff-Data.swift
  AuroraEditor/Base/Git/Models/Diff/Diff-Selection.swift
  AuroraEditor/Base/Git/Models/Diff/Raw-Diff.swift
  AuroraEditor/Base/Version Control/Model/Accounts/Bitbucket/BitbucketAccount+Token.swift
  AuroraEditor/Base/Version Control/Model/Accounts/Bitbucket/BitbucketOAuthConfiguration.swift
  AuroraEditor/Base/Version Control/Model/Accounts/Github/GithubConfiguration.swift
  AuroraEditor/Base/Version Control/Model/Accounts/Gitlab/GitlabOAuthConfiguration.swift
  AuroraEditor/Base/Version Control/Networking/Router.swift
  AuroraEditor/Base/Version Control/Networking/Session.swift
  AuroraEditor/Info.plist
  AuroraEditor/Resources/Credits.md
  AuroraEditor/Utils/Extensions/Int64.swift
Labels: documentation, Editor, Architecture, user experience

#554 Adds CursorStyles option for terminal
  Aurora Editor.xcodeproj/project.pbxproj
  AuroraEditor/Base/AppPreferences/Model/Terminal/TerminalPreferences.swift
  AuroraEditor/Base/AppPreferences/UI/TerminalPreferences/TerminalPreferencesView.swift
  AuroraEditor/Base/TerminalEmulator/UI/TerminalEmulatorView.swift
Labels: UI, bugfix, hacktoberfest, hacktoberfest-accepted

#556 Remove Typo
  README.md
Labels: Typo

#557 Fixed Welcome Window not showing on startup
  AuroraEditor/Application/AppDelegate.swift
Labels: bugfix, Verified

#560 made CONTRIBUTING.md way better, fun, precise and emojified⭐
  CONTRIBUTING.md
Labels: hacktoberfest, hacktoberfest-accepted

#561 Bug: Fixed issue where menu item can be created twice
  AuroraEditor/Application/AppDelegate.swift
  AuroraEditor/Base/MenuBarItem/StatusItem.swift
Labels: bugfix

#497 Implement Notification Support
  Aurora Editor.xcodeproj/project.pbxproj
  AuroraEditor/Application/AppDelegate.swift
  AuroraEditor/Base/AppPreferences/Model/AppPreferences.swift
  AuroraEditor/Base/AppPreferences/Model/General/GeneralPreferences.swift
  AuroraEditor/Base/AppPreferences/Model/Notifications/NotificationsPreferences.swift
  AuroraEditor/Base/AppPreferences/Model/SettingsModel.swift
  AuroraEditor/Base/AppPreferences/Model/Updates/UpdateModel.swift
  AuroraEditor/Base/AppPreferences/UI/NotificationsPreferences/NotificationPreferencesView.swift
  AuroraEditor/Base/AppPreferences/UI/PreferencesView.swift
  AuroraEditor/Base/AuroraEditorNotifications/Models/BannerModule.swift
  AuroraEditor/Base/AuroraEditorNotifications/Models/NotificationData.swift
  AuroraEditor/Base/AuroraEditorNotifications/Models/NotificationManager.swift
  AuroraEditor/Base/AuroraEditorNotifications/UI/NotificationCentreView.swift
  AuroraEditor/Base/AuroraEditorNotifications/UI/NotificationView.swift
  AuroraEditor/Base/AuroraEditorNotifications/UI/NotificationWithButton.swift
  AuroraEditor/Base/AuroraEditorNotifications/UI/NotificationWithProgress.swift
  AuroraEditor/Base/AuroraEditorUI/UI/FilterButton.swift
  AuroraEditor/Base/AuroraEditorUI/UI/Preferences/HStackToggle.swift
  AuroraEditor/Base/AuroraEditorUI/UI/Preferences/NotificationProfileToggle.swift
  AuroraEditor/Base/Documents/Model/AuroraEditorWindow/AuroraEditorWindowController+NSToolbarDelegate.swift
  AuroraEditor/Base/Documents/Model/AuroraEditorWindow/AuroraEditorWindowController.swift
  AuroraEditor/Base/Documents/UI/WorkspaceView.swift
  AuroraEditor/Base/InspectorSidebar/UI/InspectorSidebar.swift
  AuroraEditor/Base/NavigatorSidebar/UI/NavigatorSidebar.swift
  AuroraEditor/Base/NavigatorSidebar/UI/NotificationsNavigator/NotificationsNavigatorToolbarBottom.swift
  AuroraEditor/Base/NavigatorSidebar/UI/NotificationsNavigator/NotificationsNavigatorView.swift
  AuroraEditor/Base/Notification/Enums/IssueType.swift
  AuroraEditor/Base/Notification/Enums/NeverShowAgainScope.swift
  AuroraEditor/Base/Notification/Enums/NotificationChangeType.swift
  AuroraEditor/Base/Notification/Enums/NotificationType.swift
  AuroraEditor/Base/Notification/Enums/NotificationsFilter.swift
  AuroraEditor/Base/Notification/Enums/Severity.swift
  AuroraEditor/Base/Notification/Models/NotificationObserver.swift
  AuroraEditor/Base/Notification/Models/NotificationService.swift
  AuroraEditor/Base/Notification/Models/NotificationsModel.swift
  AuroraEditor/Base/Notification/Protocols/INeverShowAgainOptions.swift
  AuroraEditor/Base/Notification/Protocols/INotification.swift
  AuroraEditor/Base/Notification/Protocols/INotificationHandle.swift
  AuroraEditor/Base/Notification/Protocols/INotificationProperties.swift
  AuroraEditor/Base/Notification/Protocols/INotificationService .swift
  AuroraEditor/Base/Notification/Protocols/INotificationsModel.swift
  AuroraEditor/Base/Notification/UI/NotificationIcon.swift
  AuroraEditor/Base/Notification/UI/NotificationIndicators.swift
  AuroraEditor/Base/Notification/UI/NotificationToastView.swift
  AuroraEditor/Base/Notification/UI/NotificationViewAnimator.swift
  AuroraEditor/Base/Notification/UI/NotificationViewItem.swift
  AuroraEditor/Base/Notification/UI/ToolbarNotificationButtonView.swift
  AuroraEditor/Base/Storage/LocalStorage.swift
  AuroraEditor/Base/Toolbar/UI/ToolbarAppInfo.swift
  AuroraEditor/Base/Toolbar/UI/ToolbarAppInfoViewController.swift
  AuroraEditor/Utils/Extensions/View.swift
  AuroraEditor/Utils/Modifiers/FontWithLineHeight.swift
Labels: Architecture, hacktoberfest, hacktoberfest-accepted, Notification System, API

#567 Extension support title on notification + notification size changes
  AuroraEditor/Base/Documents/UI/WorkspaceView.swift
  AuroraEditor/Base/Notification/UI/NotificationToastView.swift
Labels: enhancement, bugfix, hacktoberfest, Extension, Notification System

#563 Bug: Theme issue on launch
  Aurora Editor.xcodeproj/xcshareddata/xcschemes/AEUpdateService.xcscheme
  AuroraEditor/Base/AppPreferences/Model/General/GeneralPreferences.swift
  AuroraEditor/Base/AppPreferences/Model/ThemePreferences/ThemeModel.swift
  AuroraEditor/Base/Editor/CodeEditorView/UI/CodeView.swift
Labels: bugfix, hacktoberfest, hacktoberfest-accepted
