Repository AuroraEditor/AuroraEditor, pull requests merged in 2023-01, with the labels that each got.

#357 Update automatic update screen (make it more clear)
  AuroraEditor/Base/AppPreferences/UI/UpdatesPreferences/UpdatePreferencesView.swift
Labels: enhancement, UI

#358 Remove padding, so the button looks OK on smaller screens too, fixes #356
  AuroraEditor/Base/NavigatorSidebar/UI/ExtensionNavigator/Explore/ExploreItemView.swift
Labels: UI, bugfix

#360 Better naming of sidebar functions-variables
  AuroraEditor/Base/Documents/Model/AuroraEditorWindow/AuroraEditorWindowController+NSToolbarDelegate.swift
Labels: Architecture, cleanup

#362 Implement `openSettings`, #284
  AuroraEditor/Application/AppDelegate.swift
  AuroraEditor/Base/Documents/Model/AuroraEditorWindow/AuroraEditorWindowController.swift
  AuroraEditor/Base/Documents/Model/WorkspaceDocument/AuroraCommandBroadcaster.swift
  AuroraEditor/Base/Documents/UI/WorkspaceView.swift
Labels: enhancement, Extension

#363 Implemented showNotification, showWarning, showError
  AuroraEditor/Base/Documents/Model/AuroraEditorWindow/AuroraEditorWindowController+NSToolbarDelegate.swift
  AuroraEditor/Base/Documents/Model/WorkspaceDocument/WorkspaceDocument.swift
  AuroraEditor/Base/Documents/UI/WorkspaceView.swift
  AuroraEditor/Base/Toolbar/UI/ToolbarAppInfo.swift
Labels: enhancement, Extension

#366 Implement ToolbarPopoverView
  AuroraEditor/Base/Toolbar/UI/ToolbarAppInfo.swift
Labels: enhancement, UI

#367 Updated settings view
  AuroraEditor.xcodeproj/project.pbxproj
  AuroraEditor/Application/AppDelegate.swift
  AuroraEditor/Base/About/UI/AboutView.swift
  AuroraEditor/Base/AppPreferences/Model/SettingItem.swift
  AuroraEditor/Base/AppPreferences/Model/SettingsModel.swift
  AuroraEditor/Base/AppPreferences/UI/LocationsPreferences/LocationsPreferencesView.swift
  AuroraEditor/Base/AppPreferences/UI/PreferencesView.swift
  AuroraEditor/Base/CommandPalette/Model/WorkspaceDocument+Commands.swift
  AuroraEditor/Base/MenuBarItem/StatusItem.swift
  Package.resolved
Labels: cleanup

#369 Allow the opening of windows and sheets in extensions.
  AuroraEditor/Base/Documents/Model/WorkspaceDocument/WorkspaceDocument+Tabs.swift
  AuroraEditor/Base/Documents/UI/WorkspaceView.swift
  AuroraEditor/Base/TabBar/Model/TabBarItemID.swift
  Package.resolved
Labels: enhancement, UI, Extension

#371 Oniguruma is working now
  AuroraEditor.xcodeproj/project.pbxproj
  AuroraEditor/Application/AppDelegate.swift
  Package.resolved
Labels: enhancement

#372 About view changes
  AuroraEditor.xcodeproj/project.pbxproj
  AuroraEditor/Application/AppDelegate.swift
  AuroraEditor/Base/About/UI/AboutView.swift
  AuroraEditor/Base/AppPreferences/UI/GeneralPreferences/GeneralPreferencesView.swift
  AuroraEditor/Base/AppPreferences/UI/GeneralPreferences/GeneralPreferencesViewSections.swift
  AuroraEditor/Base/AppPreferences/UI/SourceControlPreferences/SourceControlGeneralView.swift
  AuroraEditor/Base/CommandPalette/Model/WorkspaceDocument+Commands.swift
  AuroraEditor/Base/MenuBarItem/StatusItem.swift
  AuroraEditor/Utils/VibrantEffect.swift
  Package.resolved
Labels: enhancement, UI

#373 Enabled swiftlint rule: multiline_parameters
  .swiftlint.yml
  AuroraEditor/Base/Git/Models/Diff/Diff-Data.swift
  AuroraEditor/Base/Git/Models/Diff/Diff-Line.swift
  AuroraEditor/Base/Git/Models/IProgress.swift
  AuroraEditor/Base/NavigatorSidebar/Model/HierarchyNavigator/TabHierarchyOutlineDataSource.swift
  AuroraEditor/Base/NavigatorSidebar/Model/HierarchyNavigator/TabHierarchyOutlineDelegate.swift
  AuroraEditor/Base/NavigatorSidebar/Model/ProjectNavigator/ProjectNavigatorOutlineDataSource.swift
  AuroraEditor/Base/NavigatorSidebar/Model/ProjectNavigator/ProjectNavigatorOutlineDelegate.swift
  AuroraEditor/Base/NavigatorSidebar/Model/SourceControlNavigator/Changes/SourceControlController.swift
  AuroraEditor/Base/NavigatorSidebar/Model/SourceControlNavigator/Repositories/RepositoriesViewController.swift
  AuroraEditor/Base/Version Control/Model/Accounts/Bitbucket/BitbucketOAuthConfiguration.swift
  AuroraEditor/Base/Version Control/Model/Accounts/Github/GithubConfiguration.swift
  AuroraEditor/Base/Version Control/Model/Accounts/Github/Model/Issue.swift
  AuroraEditor/Base/Version Control/Model/Accounts/Gitlab/GitlabOAuthConfiguration.swift
  AuroraEditor/Base/Version Control/Networking/Router.swift
  AuroraEditor/Base/Version Control/UI/Actions/Cell/Workflow/WorkflowViewController.swift
  AuroraEditor/Services/Manager/AuroraNetworking.swift
  AuroraEditor/Utils/KeyChain/AuroraEditorKeychain.swift
Labels: SwiftLint

#377 Consistent naming
  .gitignore
  .swiftlint.yml
  AuroraEditor.xcodeproj/project.pbxproj
  AuroraEditor/Application/AppDelegate.swift
  AuroraEditor/Base/AppPreferences/Resources/AuroraEditor
  AuroraEditor/Utils/Log/Using Logger.md
  OpenWithAuroraEditor/FinderSync.swift
Labels: Architecture, SwiftLint

#381 Redesign about window for a more cleaner design
  Aurora Editor.xcodeproj/project.pbxproj
  AuroraEditor/Application/AppDelegate.swift
  AuroraEditor/Base/About/Model/AboutViewModal.swift
  AuroraEditor/Base/About/Model/Contributor.swift
  AuroraEditor/Base/About/UI/AboutView.swift
  AuroraEditor/Base/About/UI/ApplicationsDetailsView.swift
  AuroraEditor/Base/About/UI/ContributersDetailView.swift
  AuroraEditor/Base/About/UI/CreditsDetailView.swift
  AuroraEditor/Base/About/UI/LicenseDetailView.swift
  AuroraEditor/Resources/Credits.md
  AuroraEditor/Resources/License.md
  AuroraEditor/Utils/Version Control/Avatar.swift
Labels: enhancement, cleanup

#393 New version to sync with development
  .github/workflows/sync-main.yml
Labels: automerge

#395 Sync Main to Development
  README.md
Labels: automerge

#399 Add script that allows easing development issues
  Aurora Editor.xcodeproj/project.pbxproj
  Tools/ClearDerivedData.sh
  Tools/sort-Xcode-project-file.pl
  Tools/unused_strings.py
Labels: Script

#401 Extract strings from swift files using swift script
  Aurora Editor.xcodeproj/project.pbxproj
  Tools/xstrings.swift
Labels: Script

#403 Update checkout to v3 for `workflow.yml`
  .github/workflows/workflow.yml
Labels: GitHub Actions

#407 Sync dev with main.
  .github/workflows/sync-main.yml
  .github/workflows/workflow.yml
  Aurora Editor.xcodeproj/project.pbxproj
  README.md
  Tools/ClearDerivedData.sh
  Tools/sort-Xcode-project-file.pl
  Tools/unused_strings.py
  Tools/xstrings.swift
Labels: automerge

#412 Let nightly build on development branch
  .github/workflows/nightly.yml
Labels: GitHub Actions
