Repository AuroraEditor/AuroraEditor, pull requests merged in 2023-11, with the labels that each got.

#574 Improve extensions
  AuroraEditor/Base/CommandPalette/Model/WorkspaceDocument+Commands.swift
  AuroraEditor/Base/Documents/Model/AuroraEditorWindow/AuroraEditorWindowController.swift
  AuroraEditor/Base/Documents/Model/WorkspaceDocument/AuroraCommandBroadcaster.swift
  AuroraEditor/Base/Documents/UI/WorkspaceView.swift
  AuroraEditor/Base/Extensions/Models/ExtensionsManager.swift
  AuroraEditor/Base/NavigatorSidebar/Model/ProjectNavigator/ProjectNavigatorViewController.swift
Labels: enhancement, UI, Editor, Architecture, bugfix, Inspector, cleanup, Extension, Toolbar, Tabbar, Statusbar, user experience

#578 Add timeout limit to actions
  .github/workflows/add-to-project.yml
  .github/workflows/build-and-lint.yml
  .github/workflows/nightly.yml
  .github/workflows/sonarbuild.yml
  .github/workflows/sync-main.yml
Labels: enhancement, GitHub Actions

#596 Resign on sign error (fixes #595)
  Aurora Editor.xcodeproj/xcshareddata/xcschemes/AEUpdateService.xcscheme
  AuroraEditor/Base/Extensions/Models/ExtensionsManager.swift
Labels: enhancement, bugfix, Extension

#598 Lower build target
  Aurora Editor.xcodeproj/project.pbxproj
  AuroraEditor/Base/Extensions/Models/ExtensionsManager.swift
Labels: bugfix

#610 Make navigator button non-focusable, fixes #609
  AuroraEditor/Base/NavigatorSidebar/UI/NavigatorSidebarToolbar.swift
  AuroraEditor/Base/NavigatorSidebar/UI/ProjectNavigator/ProjectNavigatorToolbarBottom.swift
Labels: UI, bugfix

#611 Open notification pane when clicking on a notification badge
  AuroraEditor/Base/NavigatorSidebar/UI/NavigatorSidebar.swift
  AuroraEditor/Base/Notification/UI/ToolbarNotificationButtonView.swift
Labels: UI, bugfix, user experience

#613 Delete .all-contributorsrc
  .all-contributorsrc
Labels: cleanup

#615 Improved about screen
  Aurora Editor.xcodeproj/project.pbxproj
  AuroraEditor/Base/About/Controller/AboutWindowHostingController.swift
  AuroraEditor/Base/About/Model/AboutViewModal.swift
  AuroraEditor/Base/About/Model/Contributor.swift
  AuroraEditor/Base/About/UI/AboutView.swift
  AuroraEditor/Base/About/UI/ContributersDetailView.swift
  AuroraEditor/Base/About/UI/ContributorsDetailView.swift
  AuroraEditor/Base/About/UI/LicenseDetailView.swift
  AuroraEditor/Base/AuroraEditorUI/UI/CachingAsyncImageView.swift
  AuroraEditor/Base/AuroraEditorUI/UI/CachingImageView.swift
  AuroraEditor/Resources/License.md
  AuroraEditor/Utils/Extensions/NSImage.swift
  AuroraEditor/Utils/ImageCache.swift
  AuroraEditor/Utils/Version Control/Avatar.swift
Labels: UI, Editor, user experience

#616 Update Beta branch
  .all-contributorsrc
  .github/workflows/sonarbuild.yml
  .github/workflows/test.yml
  AEUpdateService/Animation/Loader.swift
  AEUpdateService/ContentView.swift
  AEUpdateService/Main.swift
  Aurora Editor.xcodeproj/project.pbxproj
  Aurora Editor.xcodeproj/xcshareddata/xcschemes/Aurora Editor (Tests).xcscheme
  AuroraEditor/Base/About/Controller/AboutWindowHostingController.swift
  AuroraEditor/Base/About/Model/AboutViewModal.swift
  AuroraEditor/Base/About/Model/Contributor.swift
  AuroraEditor/Base/About/UI/AboutView.swift
  AuroraEditor/Base/About/UI/ContributersDetailView.swift
  AuroraEditor/Base/About/UI/ContributorsDetailView.swift
  AuroraEditor/Base/About/UI/LicenseDetailView.swift
  AuroraEditor/Base/AuroraEditorUI/UI/CachingAsyncImageView.swift
  AuroraEditor/Base/AuroraEditorUI/UI/CachingImageView.swift
  AuroraEditor/Base/NavigatorSidebar/UI/NavigatorSidebar.swift
  AuroraEditor/Base/NavigatorSidebar/UI/NavigatorSidebarToolbar.swift
  AuroraEditor/Base/NavigatorSidebar/UI/ProjectNavigator/ProjectNavigatorToolbarBottom.swift
  AuroraEditor/Base/Notification/UI/NotificationToastView.swift
  AuroraEditor/Base/Notification/UI/ToolbarNotificationButtonView.swift
  AuroraEditor/Resources/License.md
  AuroraEditor/Utils/Extensions/NSImage.swift
  AuroraEditor/Utils/ImageCache.swift
  AuroraEditor/Utils/Version Control/Avatar.swift
  README.md
Labels: Synchronize

#619 Migration: Migrated old version control code to the new version control code
  Aurora Editor.xcodeproj/project.pbxproj
  AuroraEditor/Base/NavigatorSidebar/Model/SourceControlNavigator/Changes/Utils/CommitMessageFormatter.swift
  AuroraEditor/Base/NavigatorSidebar/Model/SourceControlNavigator/Repositories/RepositoriesMenu.swift
  AuroraEditor/Base/NavigatorSidebar/Model/SourceControlNavigator/Repositories/RepositoriesTableViewCell.swift
  AuroraEditor/Base/NavigatorSidebar/Model/SourceControlNavigator/Repositories/RepositoryModel.swift
  AuroraEditor/Base/NavigatorSidebar/UI/SourceControlNavigator/Repositories/CreateNewRepositoryView.swift
  AuroraEditor/Base/Toolbar/UI/ToolbarBranchPicker.swift
  AuroraEditor/Base/Version Control/Model/Actions/GitHubActionsModel.swift
  AuroraEditor/Base/Version Control/Model/Client/Core/GitClient.swift
  AuroraEditor/Base/Version Control/Model/Project History/BranchCommitHistory.swift
  AuroraEditor/Base/Version Control/Model/Project History/ProjectCommitHistory.swift
  AuroraEditor/Base/Version Control/UI/Branch/CreateNewBranchView.swift
  AuroraEditor/Base/Version Control/UI/Clone/CheckoutBranch.swift
  AuroraEditor/Base/Version Control/UI/Clone/GitCloneView+Helpers.swift
  AuroraEditor/Base/Version Control/UI/Clone/GitCloneView.swift
  AuroraEditor/Base/Version Control/UI/Project History/BranchCommitHistoryView.swift
  AuroraEditor/Base/Version Control/UI/Project History/Cell/CommitHistoryCellView.swift
  AuroraEditor/Base/Version Control/UI/Project History/ProjectCommitHistoryView.swift
  AuroraEditor/Base/Version Control/UI/Remote/AddRemoteView.swift
  AuroraEditor/Base/Version Control/UI/Rename/RenameBranchView.swift
Labels: Architecture, Version control

#624 Temporary fix for iCloud enabled folders, fixes #623
  Aurora Editor.xcodeproj/project.pbxproj
  AuroraEditor/Base/NavigatorSidebar/Model/SourceControlNavigator/Changes/Utils/CommitMessageFormatter.swift
  AuroraEditor/Base/NavigatorSidebar/Model/SourceControlNavigator/Repositories/RepositoriesMenu.swift
  AuroraEditor/Base/NavigatorSidebar/Model/SourceControlNavigator/Repositories/RepositoriesTableViewCell.swift
  AuroraEditor/Base/NavigatorSidebar/Model/SourceControlNavigator/Repositories/RepositoryModel.swift
  AuroraEditor/Base/NavigatorSidebar/UI/SourceControlNavigator/Repositories/CreateNewRepositoryView.swift
  AuroraEditor/Base/Toolbar/UI/ToolbarBranchPicker.swift
  AuroraEditor/Base/Version Control/Model/Actions/GitHubActionsModel.swift
  AuroraEditor/Base/Version Control/Model/Client/Core/GitClient.swift
  AuroraEditor/Base/Version Control/Model/Project History/BranchCommitHistory.swift
  AuroraEditor/Base/Version Control/Model/Project History/ProjectCommitHistory.swift
  AuroraEditor/Base/Version Control/UI/Branch/CreateNewBranchView.swift
  AuroraEditor/Base/Version Control/UI/Clone/CheckoutBranch.swift
  AuroraEditor/Base/Version Control/UI/Clone/GitCloneView+Helpers.swift
  AuroraEditor/Base/Version Control/UI/Clone/GitCloneView.swift
  AuroraEditor/Base/Version Control/UI/Project History/BranchCommitHistoryView.swift
  AuroraEditor/Base/Version Control/UI/Project History/Cell/CommitHistoryCellView.swift
  AuroraEditor/Base/Version Control/UI/Project History/ProjectCommitHistoryView.swift
  AuroraEditor/Base/Version Control/UI/Remote/AddRemoteView.swift
  AuroraEditor/Base/Version Control/UI/Rename/RenameBranchView.swift
Labels: bugfix
